### ISSUE TITLE
New angles package breaks the code, but here's the fix

### ISSUE THREAD

**Issue by MTMurphy77** [jbwhit/dipole_error#1]
It seems that there's a new angles package, and that means that the following replacement needs to be made in dipole_error.py in at lines 181, 268 and 346:

#    pos1 = angles.AngularPosition(alpha=right_ascension, delta=declination)
    pos1 = angles.AngularPosition.from_hd(hd=right_ascension+" "+declination)

This also has implications for the format of the input RA and Dec., in that no longer does
QSO_RA = "05h17m07.62" # RA
QSO_DEC = "-44d10m55.6" # DEC
work and you must just use
QSO_RA = "05 17 07.62" # RA
QSO_DEC = "-44 10 55.6" # DEC

I've made the replacements above in the attached dipole_error.py and example.py replacement scripts.
[Archive.zip](https://github.com/jbwhit/dipole_error/files/122642/Archive.zip)

**Comment by jbwhit** [comment]
Thanks, I've incorporated it into the package; bumped version to 2.0.0. `pip install -U dipole_error` should do it!
